### ISSUE TITLE
How to add new road map

### ISSUE THREAD

**Issue by AshirMehmood** [BuildersChain/Developers-Roadmap#12]
### Description

how to add a roadmap in a efficient manner?

**Comment by yashdev9274** [comment]
Good question @AshirMehmood 

Check out [Javascript-roadmap.md](https://github.com/BuildersChain/Developers-Roadmap/blob/main/Frontend-Developer/JavaScript/Javascript-roadmap.md) file to understand how you have to create roadmap, create files and folders according to the requirement

Before adding new roadmap, create such kind of file and open issue  so that we can review it and suggest you changes, and then you can raise PR
